%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-ethercat-grant
Version:        0.2.5
Release:        7%{?dist}%{?release_suffix}
Summary:        ROS ethercat_grant package

License:        BSD
URL:            http://www.shadowrobot.com/
Source0:        %{name}-%{version}.tar.gz

Requires:       libcap-devel
Requires:       ros-noetic-roscpp
BuildRequires:  libcap-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-roscpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Makes it possible to run the ros_ethercat_loop without using sudo. Forked from
pr2-grant

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri May 28 2021 Shadow Robot's software team <software@shadowrobot.com> - 0.2.5-7
- Autogenerated by Bloom

* Fri May 28 2021 Shadow Robot's software team <software@shadowrobot.com> - 0.2.5-6
- Autogenerated by Bloom

* Tue Apr 27 2021 Shadow Robot's software team <software@shadowrobot.com> - 0.2.5-5
- Autogenerated by Bloom

* Tue Apr 27 2021 Shadow Robot's software team <software@shadowrobot.com> - 0.2.5-4
- Autogenerated by Bloom

* Tue Apr 27 2021 Shadow Robot's software team <software@shadowrobot.com> - 0.2.5-3
- Autogenerated by Bloom

